### PR TITLE
update to version 0.8.2

### PR DESCRIPTION
**Pull request by murrayrm**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

<!--
Please add any other relevant info below:
→
Not sure I need to re-rerender.  Link not working?

### CODE REVIEW

**Comment by murrayrm** [comment]
@conda-forge-admin, please rerender

**Comment by murrayrm** [comment]
@moorepants Any hints about what might be going wrong here?  Looks like things are working except linux/python 2.7.  ??

**Comment by moorepants** [comment]
I still haven't figured out how to see the logs on these new azure builds.

**Comment by moorepants** [comment]
Here is the error:

```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
WARNING: symlink_conda() is deprecated.
export PREFIX=/home/conda/feedstock_root/build_artifacts/control_1555480995458/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/control_1555480995458/test_tmp
import: 'control'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/control_1555480995458/test_tmp/run_test.py", line 2, in <module>
    import control
  File "/home/conda/feedstock_root/build_artifacts/control_1555480995458/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/control/__init__.py", line 52, in <module>
    from .freqplot import *
  File "/home/conda/feedstock_root/build_artifacts/control_1555480995458/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/control/freqplot.py", line 44, in <module>
    import matplotlib.pyplot as plt
  File "/home/conda/feedstock_root/build_artifacts/control_1555480995458/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/conda/feedstock_root/build_artifacts/control_1555480995458/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/home/conda/feedstock_root/build_artifacts/control_1555480995458/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/home/conda/feedstock_root/build_artifacts/control_1555480995458/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/home/conda/feedstock_root/build_artifacts/control_1555480995458/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/home/conda/feedstock_root/build_artifacts/control_1555480995458/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/home/conda/feedstock_root/build_artifacts/control_1555480995458/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/site-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/home/conda/feedstock_root/build_artifacts/control_1555480995458/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python2.7/lib-tk/Tkinter.py", line 39, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libX11.so.6: cannot open shared object file: No such file or directory
Tests failed for control-0.8.2-py27_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for control-0.8.2-py27_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: control-0.8.2-py27_0.tar.bz2
##[error]Bash exited with code '1'.
##[section]Finishing: Run docker build
```

**Comment by moorepants** [comment]
It seems like matplotlib is not installing its dependencies. Did mpl drop Py 2.7 support maybe?

**Comment by moorepants** [comment]
I might try this:

```
- matplotlib <3.0 # [py27]
- matplotlib  # [not py27]
```

**Comment by murrayrm** [comment]
Thanks!  I'll check into this as soon as I get a chance.

**Comment by murrayrm** [comment]
Indeed, matplotlib 3.0 requires python >= 3.5, so that is likely the problem.  More here:

  https://github.com/matplotlib/matplotlib/issues/9404/

**Comment by murrayrm** [comment]
Still failing, same error (using matplotlib 2.2)

**Comment by murrayrm** [comment]
@conda-forge/core Having trouble with `matplotlib` on a linux py27 build.  Missing X11 library.  Tried hunting around, but can't figure out what is causing the problems (works on all other platforms/python versions).  Any thoughts?

**Comment by murrayrm** [comment]
Tried a couple of (unsuccessful) things to see if I could get this to work.  Putting in X11 explicitly didn't solve the problem.

Some related posts:
* https://github.com/neuropoly/spinalcordtoolbox/issues/782
* https://stackoverflow.com/questions/46613117/why-does-conda-install-tk-not-work-in-my-docker-container-even-though-it-says-it?noredirect=1&lq=1

The second of these indicates that perhaps the problem is that the docker image that is being used doesn't have a virtual framebuffer installed (?).

**Comment by moorepants** [comment]
@conda-forge/python Can any of the conda forge python moderators help us on this?

**Comment by moorepants** [comment]
Maybe try the yum_requirements.txt file to install it: https://github.com/conda-forge/itkwidgets-feedstock/pull/6

**Comment by moorepants** [comment]
Or maybe this: https://github.com/conda-forge/staged-recipes/pull/8058/commits/87fc8611f4c6baa5f6a0343b236ed36a0bed7060

**Comment by moorepants** [comment]
There is also this CDT stuff:

https://github.com/conda-forge/oommf-feedstock/pull/13

**Comment by ocefpaf** [comment]
> @conda-forge/python Can any of the conda forge python moderators help us on this?

I don't think you want the conda-forge Python maintainers here. You probably wanted to ping `@conda-forge/core`. I'll take a look at this soon but if the issue is CDTs please take a look at https://conda-forge.org/docs/maintainer/knowledge_base.html#core-dependency-tree-packages-cdt

**Comment by murrayrm** [comment]
@conda-forge-admin, please rerender

**Comment by murrayrm** [comment]
Adding `mesa-libGL` to `yum_requirements.txt` fixed the problem.  Thanks for chasing down that suggestion, @moorepants!

**Pull request merged**
